version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: tasks
      POSTGRES_PASSWORD: "eeun7W6yf7iLM-DYGmJzny-OMf5XPej7"
    volumes:
      - tasks_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "_vFFZaamtx6ISGBMWTx-g96nD_SN2uoF"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  tasks_data:
